Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection & Analysis

In [ ]:
# loading the data from csv file to a Pandas DataFrame
parkinsons_data = pd.read_csv('/content/parkinsons.csv')

In [ ]:
# printing the first 5 rows of the dataframe
parkinsons_data.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1.0,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1.0,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1.0,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1.0,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1.0,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [ ]:
# number of rows and columns in the dataframe
parkinsons_data.shape

(1195, 24)

In [ ]:
# getting more information about the dataset
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1195 entries, 0 to 1194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              1195 non-null   object
 1   MDVP:Fo(Hz)       1195 non-null   float64
 2   MDVP:Fhi(Hz)      1195 non-null   float64
 3   MDVP:Flo(Hz)      1195 non-null   float64
 4   MDVP:Jitter(%)    1195 non-null   float64
 5   MDVP:Jitter(Abs)  1195 non-null   float64
 6   MDVP:RAP          1195 non-null   float64
 7   MDVP:PPQ          1195 non-null   float64
 8   Jitter:DDP        1195 non-null   float64
 9   MDVP:Shimmer      1195 non-null   float64
 10  MDVP:Shimmer(dB)  1195 non-null   float64
 11  Shimmer:APQ3      1195 non-null   float64
 12  Shimmer:APQ5      1195 non-null   float64
 13  MDVP:APQ          1195 non-null   float64
 14  Shimmer:DDA       1195 non-null   float64
 15  NHR               1195 non-null   float64
 16  HNR               1195 non-null   float64
 17  status            1195 non-null   float64
 18  RPDE              1195 non-null   float64
 19  DFA               1195 non-null   float64
 20  spread1           1195 non-null   float64
 21  spread2           1195 non-null   float64
 22  D2                1195 non-null   float64
 23  PPE               1195 non-null   float64
dtypes: float64(23), object(1)
memory usage: 224.2+ KB

In [ ]:
# checking for missing values in each column
parkinsons_data.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [ ]:
# getting some statistical measures about the data
parkinsons_data.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,...,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000,1195.000000
mean,154.312848,197.246916,116.332971,0.006221,0.000044,0.003306,0.003428,0.009920,0.029671,0.282587,...,0.047084,0.024880,21.895992,0.754117,0.498054,0.718214,-5.683541,0.226451,2.382126,0.206771
std,17.124313,37.804828,17.953210,0.002001,0.000014,0.001228,0.001140,0.003678,0.007781,0.080554,...,0.012609,0.016717,1.829752,0.178176,0.043021,0.022905,0.451130,0.034527,0.157783,0.037229
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,150.616420,189.666263,112.204966,0.005769,0.000041,0.003012,0.003173,0.009089,0.027992,0.264388,...,0.044325,0.020837,21.550002,0.726172,0.489091,0.713742,-5.779205,0.219263,2.351569,0.199061
50%,154.117666,197.198334,116.100612,0.006188,0.000044,0.003282,0.003397,0.009845,0.029575,0.280555,...,0.046820,0.024486,21.913050,0.758665,0.497781,0.718387,-5.681992,0.226621,2.382482,0.207056
75%,157.491303,204.071906,119.290367,0.006557,0.000046,0.003530,0.003618,0.010552,0.031008,0.296840,...,0.049418,0.027661,22.274815,0.797437,0.506417,0.722957,-5.595197,0.232901,2.411210,0.213564
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

In [ ]:
# distribution of target Variable
parkinsons_data['status'].value_counts()

status
1.000000    147
0.000000     48
0.775340      1
0.748202      1
0.793314      1
           ...
0.758922      1
0.722024      1
0.750154      1
0.726512      1
0.740147      1
Name: count, Length: 1002, dtype: int64

1  --> Parkinson's Positive

0 --> Healthy

In [ ]:
# grouping the data based on the target variable
parkinsons_data.drop('name', axis=1).groupby('status').mean()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
status,,,,,,,,,,,,,,,,,,,,,
0.000000,181.937771,223.636750,145.207292,0.003866,0.000023,0.001925,0.002056,0.005776,0.017615,0.162958,...,0.013305,0.028511,0.011483,24.678750,0.442552,0.695716,-6.759264,0.160292,2.154491,0.123017
0.575556,149.198447,207.415543,111.482874,0.006078,0.000040,0.003701,0.003331,0.008534,0.031243,0.275112,...,0.024103,0.049216,0.026544,21.318538,0.501891,0.725354,-5.564950,0.209877,2.380827,0.206444
0.615667,153.886563,199.401599,121.363146,0.005983,0.000047,0.003138,0.003550,0.009534,0.026432,0.282593,...,0.023219,0.048064,0.034362,22.159939,0.493306,0.721284,-5.490661,0.214860,2.363735,0.225016
0.625442,152.157607,207.259044,116.464707,0.005995,0.000044,0.003535,0.003458,0.010400,0.032165,0.256628,...,0.024626,0.047195,0.020836,21.418531,0.477161,0.718057,-5.581980,0.225841,2.369936,0.211201
0.627344,153.080931,202.680710,113.269057,0.006523,0.000046,0.003239,0.003415,0.009060,0.029728,0.271875,...,0.024869,0.048402,0.022129,21.939683,0.498502,0.723707,-5.823857,0.221358,2.384068,0.195353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.865840,152.466878,192.782541,120.296634,0.005874,0.000044,0.003664,0.003540,0.010088,0.029207,0.309389,...,0.026209,0.048204,0.027789,21.525414,0.493623,0.717218,-5.698483,0.218747,2.350404,0.193617
0.875026,159.428126,188.703201,113.941707,0.006447,0.000041,0.002958,0.003123,0.008723,0.029753,0.290140,...,0.025242,0.043531,0.025270,21.984162,0.510846,0.718195,-5.670870,0.228618,2.354472,0.197873
0.877561,155.771643,195.171568,115.100600,0.005912,0.000049,0.002894,0.003737,0.009543,0.026965,0.313777,...,0.025692,0.044149,0.027168,20.991225,0.500720,0.719314,-5.711304,0.230594,2.399800,0.209875
0.903225,155.123225,192.644017,117.508194,0.006310,0.000039,0.002945,0.003067,0.010481,0.032074,0.273438,...,0.024033,0.045627,0.017167,22.511802,0.478040,0.714276,-5.732308,0.222163,2.379702,0.188154
1.000000,145.180762,188.441463,106.893558,0.006989,0.000051,0.003757,0.003900,0.011273,0.033658,0.321204,...,0.027600,0.053027,0.029211,20.974048,0.516816,0.725408,-5.333420,0.248133,2.456058,0.233828

Data Pre-Processing

Separating the features & Target

In [ ]:
X = parkinsons_data.drop(columns=['name','status'], axis=1)
Y = parkinsons_data['status'].round().astype(int)

In [ ]:
print(X)

      MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0      119.992000    157.302000     74.997000        0.007840
1      122.400000    148.650000    113.819000        0.009680
2      116.682000    131.111000    111.555000        0.010500
3      116.676000    137.871000    111.366000        0.009970
4      116.014000    141.781000    110.655000        0.012840
...           ...           ...           ...             ...
1190   151.028206    179.206312    118.797466        0.006594
1191   161.752472    211.299774    114.784598        0.006397
1192   148.323186    194.399282    118.570170        0.006335
1193   152.106305    209.880095    112.903699        0.005298
1194   151.964173    211.553642    120.752900        0.005573

      MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.000070  0.003700  0.005540    0.011090      0.043740
1             0.000080  0.004650  0.006960    0.013940      0.061340
2             0.000090  0.005440  0.007810    0.016330      0.052330
3             0.000090  0.005020  0.006980    0.015050      0.054920
4             0.000110  0.006550  0.009080    0.019660      0.064250
...                ...       ...       ...         ...           ...
1190          0.000040  0.003458  0.003513    0.008731      0.027186
1191          0.000045  0.003545  0.003017    0.009591      0.028982
1192          0.000044  0.003483  0.003386    0.008980      0.029598
1193          0.000041  0.002778  0.003506    0.009388      0.029550
1194          0.000040  0.003039  0.002910    0.011217      0.031296

      MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA       NHR        HNR  \
0             0.426000  ...  0.029710     0.065450  0.022110  21.033000
1             0.626000  ...  0.043680     0.094030  0.019290  19.085000
2             0.482000  ...  0.035900     0.082700  0.013090  20.651000
3             0.517000  ...  0.037720     0.087710  0.013530  20.644000
4             0.584000  ...  0.044650     0.104700  0.017670  19.649000
...                ...  ...       ...          ...       ...        ...
1190          0.265100  ...  0.024836     0.050788  0.021377  21.884979
1191          0.301784  ...  0.024254     0.049785  0.020925  21.973752
1192          0.290663  ...  0.024838     0.051215  0.021530  21.615298
1193          0.289629  ...  0.025529     0.049023  0.026806  21.561977
1194          0.335169  ...  0.023404     0.049004  0.020198  21.637952

          RPDE       DFA   spread1   spread2        D2       PPE
0     0.414783  0.815285 -4.813031  0.266482  2.301442  0.284654
1     0.458359  0.819521 -4.075192  0.335590  2.486855  0.368674
2     0.429895  0.825288 -4.443179  0.311173  2.342259  0.332634
3     0.434969  0.819235 -4.117501  0.334147  2.405554  0.368975
4     0.417356  0.823484 -3.747787  0.234513  2.332180  0.410335
...        ...       ...       ...       ...       ...       ...
1190  0.499528  0.727604 -5.772439  0.234236  2.392305  0.210778
1191  0.499209  0.728558 -5.604039  0.235680  2.362850  0.209570
1192  0.497459  0.717687 -5.770640  0.233789  2.410545  0.223595
1193  0.486495  0.722529 -5.677169  0.236918  2.427505  0.218734
1194  0.508520  0.720055 -5.884754  0.228012  2.395277  0.197326

[1195 rows x 22 columns]

In [ ]:
print(Y)

0       1
1       1
2       1
3       1
4       1
       ..
1190    1
1191    1
1192    1
1193    1
1194    1
Name: status, Length: 1195, dtype: int64

Splitting the data to training data & Test data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(1195, 22) (956, 22) (239, 22)

Data Standardization

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
print(X_train)

[[ 0.34188451  0.2442899   0.09663174 ... -0.0962059   0.40942251
   0.01532179]
 [-0.13876766 -0.44174706  0.08342771 ...  0.14262086  0.09241261
  -0.13698856]
 [ 0.07610682  0.02425307  0.02217056 ...  0.07477425  0.18110317
   0.1611517 ]
 ...
 [-0.11638224  0.14278774 -0.07339578 ... -0.19608135  0.08348536
   0.05138626]
 [-0.41272695  0.06767819 -0.25096113 ... -0.08719167  0.15075996
  -0.16438347]
 [-0.34146064 -0.07324915  0.10430309 ...  0.1983797   0.18269669
   0.45775209]]

Model Training

Support Vector Machine Model

In [ ]:
model = svm.SVC(kernel='linear')

In [ ]:
# training the SVM model with training data
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
print(Y_train.unique())

[1 0]

Model Evaluation

Accuracy Score

In [ ]:
# accuracy score on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [ ]:
print('Accuracy score of training data : ', training_data_accuracy)

Accuracy score of training data :  0.9832635983263598

In [ ]:
# accuracy score on training data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [ ]:
print('Accuracy score of test data : ', test_data_accuracy)

Accuracy score of test data :  0.9874476987447699

Building a Predictive System

In [ ]:
input_data = (197.07600,206.89600,192.05500,0.00289,0.00001,0.00166,0.00168,0.00498,0.01098,0.09700,0.00563,0.00680,0.00802,0.01689,0.00339,26.77500,0.422229,0.741367,-7.348300,0.177551,1.743867,0.085569)

# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the data
std_data = scaler.transform(input_data_reshaped)

prediction = model.predict(std_data)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not have Parkinsons Disease")

else:
  print("The Person has Parkinsons")

[0]
The Person does not have Parkinsons Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Saving the trained model

In [ ]:
import pickle

In [ ]:
filename = 'parkinsons_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
# loading the saved model
loaded_model = pickle.load(open('parkinsons_model.sav', 'rb'))

In [ ]:
for column in X.columns:
  print(column)

MDVP:Fo(Hz)
MDVP:Fhi(Hz)
MDVP:Flo(Hz)
MDVP:Jitter(%)
MDVP:Jitter(Abs)
MDVP:RAP
MDVP:PPQ
Jitter:DDP
MDVP:Shimmer
MDVP:Shimmer(dB)
Shimmer:APQ3
Shimmer:APQ5
MDVP:APQ
Shimmer:DDA
NHR
HNR
RPDE
DFA
spread1
spread2
D2
PPE